.TH Cronos II
.SH NAME
Cronos II \- A powerful GNOME mail client.
.SH SYNOPSIS
.B cronos
.SH DESCRIPTION

.B Cronos II
is powerful GNOME mail client which is very light and fast.
It's designed with all users in mind, new users, as well as
advanced users, that's why Cronos II is so highly configurable.
The default configuration is seted according to what most
users would prefer, but any user can change the program to
make his/she's own Cronos II through it's very
friendly user interface.
