.TH Cronos II
.SH NAME
Cronos II \- A powerful GNOME mail client.
.SH SYNOPSIS
.B cronos
.SH DESCRIPTION

.B Cronos II
is a powerful GNOME mail client which is very light and fast.
Designed with all users in mind, new users, as well as
advanced users,  Cronos II is  highly configurable.
The default configuration is set according to what most
users would prefer, but any user can change the program to
make his or her own Cronos II through a  very
friendly user interface. Cronos II also supports a number of extensions
(or plug-ins).
