.TH Cronos II
.SH NAME
Cronos II \- A powerful GNOME mail client.
.SH SYNOPSIS
.B cronos
.RB [ \-\^\-help ]
.SH DESCRIPTION

.B Cronos II
is a powerful GNOME mail client engineered to be quick, responsive, and
feature rich. Designed with all users in mind, neophytes as well as
advanced users will find  Cronos II a friendly and highly configurable
graphical e-mail client. Cronos II's default configuration is setup
according to the most common preferences of most users, but most options can
be easily changed through the extensive Prefernces dialog box.

Cronos II provides facility for plug-ins to add extra functionality to the
program. Please see \fIhttp://www.cronosii.net/plugins.php\fR for more information
on developing plugins or to download and use existing plugins.

.SS OPTIONS
.BI \-m ", " \-\^\-composer
Open a Composer window.

.BI \-l " mailto:email" "\fR,\fP \-\^\-link=" mailto:email
Interpret the argument as a mailto: link and open the composer
with the proper information filled in.

.SS SEE ALSO
.BI http://www.cronosii.net/
