/* Automatically generated by po2tbl.sed from cronosII-scratch.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Unable to create structure for Cronos II Db: %s\n", 2},
  {"Unable to update structure for Spool Db: %s\n", 3},
  {"Unable to create structure for Spool Db (1): %s\n", 4},
  {"Unable to create structure for Spool Db (2): %s\n", 5},
  {"Success", 6},
  {"Data exception", 7},
  {"No such message", 8},
  {"Process is busy", 9},
  {"Unknown hostname", 10},
  {"This message claims to be multipart, but is broken.", 11},
  {"This message claims to be multipart but it seems to be broken.", 12},
  {"Internal socket read operation failed", 13},
  {"Internal socket write operation failed", 14},
  {"SMTP server did not respond to our sent messaage in a friendly way", 15},
  {"System Error: Unable to write message to disk for local SMTP command", 16},
  {"Internal C2 Error: Unable to fetch headers in email message", 17},
  {"\
Problem running local SMTP command to send messages -- Check SMTP settings", 18},
  {"Unable to resolve SMTP server hostname", 19},
  {"Unable to connect to SMTP server", 20},
  {"SMTP server was not friendly on our connect! May not be RFC compliant", 21},
  {"SMTP server did not respond to 'EHLO in a friendly way", 22},
  {"SMTP server did not respond to HELO in a friendly way", 23},
  {"Internal C2 Error: Unable to fetch \"From:\" header in email message", 24},
  {"Internal C2 Error: Unable to fetch \"To:\" header in email message", 25},
  {"SMTP server did not reply to 'MAIL FROM:' in a friendly way", 26},
  {"SMTP server did not reply to 'DATA' in a friendly way", 27},
  {"SMTP server did not reply to 'RCPT TO:' in a friendly way", 28},
  {"Bad syntaxes, quotes aren't closed.\n", 29},
  {"Spool (local)", 30},
  {"Unable to create mailbox", 31},
  {"Unable to update the mailbox: Unable to find the configuration ID", 32},
  {"Unable to delete the mailbox: Unable to find the configuration ID", 33},
  {"Old configuration found, importing it...", 34},
  {"Creating new configuration due to previous error...", 35},
  {"No previous configuration found, creating new...", 36},
  {"Detecting old configuration...", 37},
  {"Wrong upgrade_database parameters", 38},
  {"Unable to open index file: %s", 39},
  {"Unable to load db: %s", 40},
  {"Unable to move the temporary file to the correct location: %s", 41},
  {"Loading old configuration", 42},
  {"Registering  the new configuration 'Version'", 43},
  {"Success.", 44},
  {"Parsing a mailbox", 45},
  {"Failed.", 46},
  {"Upgrading database", 47},
  {"Registering in the new configuration 'addrbook_init'", 48},
  {"Registering in the new configuration 'empty_garbage'", 49},
  {"Registering in the new configuration 'check_at_start'", 50},
  {"Registering in the new configuration 'use_outbox'", 51},
  {"Registering in the new configuration 'use_persistent_smtp_connection'", 52},
  {"Registering in the new configuration 'check_timeout'", 53},
  {"Registering in the new configuration 'message_size_limit'", 54},
  {"Registering in the new configuration 'net_timeout'", 55},
  {"Registering in the new configuration 'mark_as_read_timeout'", 56},
  {"Registering in the new configuration 'persistent_smtp_port'", 57},
  {"Registering in the new configuration 'prepend_character'", 58},
  {"Registering in the new configuration 'persistent_smtp_host'", 59},
  {"Registering in the new configuration 'color_reply_original_message'", 60},
  {"Registering in the new configuration 'color_misc_body'", 61},
  {"Upgrading mailboxes tree.", 62},
  {"Loading old rc configuration", 63},
  {"Registering in the new configuration 'mime_window'", 64},
  {"Registering in the new configuration 'toolbar'", 65},
  {"Registering in the new configuration 'wm_hpan'", 66},
  {"Registering in the new configuration 'wm_vpan'", 67},
  {"Registering in the new configuration 'wm_clist'", 68},
  {"Registering in the new configuration 'wm_width'", 69},
  {"Registering in the new configuration 'wm_height'", 70},
  {"Registering in the new configuration 'showable_headers:preview'", 71},
  {"Registering in the new configuration 'showable_headers:message'", 72},
  {"Registering in the new configuration 'showable_headers:compose'", 73},
  {"Registering in the new configuration 'showable_headers:save'", 74},
  {"Registering in the new configuration 'showable_headers:print'", 75},
  {"Registering in the new configuration 'font_read'", 76},
  {"Registering in the new configuration 'font_unread'", 77},
  {"Registering in the new configuration 'font_body'", 78},
  {"Registering in the new configuration 'app_title'", 79},
  {"Saving the new configuration", 80},
  {"Creating internal directory structure", 81},
  {"Creating internal file structure", 82},
  {"Configuring Cronos II", 83},
  {"Cronos II Configuration Kit", 84},
  {"Welcome to Cronos II 0.3.0", 85},
  {"\
Since this is the first time you ever used Cronos II 0.3.0\n\
your configuration must be created, in order to be able\n\
to use all of the new functions Cronos II has.\n\
\n\
Through this simple wizard you will be able to finish the\n\
installation of Cronos II in your system.\n\
\n\
To start the process, press the 'Next' button.", 86},
  {"Cronos II 0.3.0", 87},
  {"Installation complete", 88},
  {"\
The installation of Cronos II in your system is complete, you can\n\
now start it by clicking the 'Finish' button or by accessing your\n\
Gnome menu in the Net menu.\n\
\n\
Thanks for choosing Cronos II.\n\
The Cronos II Developers Team.", 89},
  {"\
The configuration wasn't generated.\n\
Quit anyway?", 90},
  {"Compose a new email.", 91},
  {"Set the Account field.", 92},
  {"Account", 93},
  {"Set the To field.", 94},
  {"Address", 95},
  {"Set the CC field.", 96},
  {"Set the BCC field.", 97},
  {"Set the Subject field.", 98},
  {"Subject", 99},
  {"Set the Body.", 100},
  {"Text", 101},
  {"Compose a new email decoding the argument as a mailto: link", 102},
  {"Check account for mail.", 103},
  {"Open the main window (default)", 104},
  {"Plain text", 105},
  {"HTML formatted", 106},
  {"Multithread", 107},
  {"Monothread", 108},
  {"Icons only", 109},
  {"Text only", 110},
  {"Icons & Text", 111},
  {"Use document specified fonts", 112},
  {"Always use my fonts", 113},
  {"Post Office Protocol 3 (POP3)", 114},
  {"Static Signature", 115},
  {"Dynamic Signature (output of commands)", 116},
  {"General", 117},
  {"Options", 118},
  {"Paths", 119},
  {"Accounts", 120},
  {"Interface", 121},
  {"Fonts", 122},
  {"Colors", 123},
  {"%s (default)", 124},
  {"Advanced", 125},
  {"Preferences", 126},
  {"Account Editor", 127},
  {"POP3", 128},
  {"IMAP", 129},
  {"SMTP", 130},
  {"Sendmail", 131},
  {"Password", 132},
  {"APOP", 133},
  {"From", 134},
  {"Date", 135},
  {"Mailbox", 136},
  {"Message Transfer", 137},
  {"\
This window shows transfer of messages (incoming and outcoming).\n\
Clicking a row on the list you will get more information  the progress of \
the transfer", 138},
  {"Waiting to get messages.", 139},
  {"Waiting to deliver a message.", 140},
  {"Connection established.", 141},
  {"Retrieving messages...", 142},
  {"No messages at server.", 143},
  {"%d messages downloaded.", 144},
  {"\
Cronos II was not able to load the UI, you should check your installation.\n\
Aborting.\n", 145},
  {"The mailbox '%s' couldn't be loaded", 146},
  {"%d messages, %d new.", 147},
  {"You found the Eastern Egg!", 148},
  {"Neat, baby!", 149},
  {"Unable to open about file", 150},
  {"New mailbox", 151},
  {"\
The account name you\n\
selected is already in use.\n\
\n\
Account names need to be unique.\n\
Please choose another one.", 152},
  {"Error", 153},
  {"Close Dialog", 154},
  {"\
The E-Mail address you\n\
entered is not valid.", 155},
  {"\
The account name you\n\
entered is not valid.", 156},
  {"You have not entered a valid hostname.", 157},
  {"\
This will permanently remove\n\
the account from your configuration.\n\
\n\
Are you sure you want this?", 158},
  {"Confirmation", 159},
  {"Information", 160},
  {"Actions at start", 161},
  {"Check for mail in active accounts.", 162},
  {"Load mailboxes", 163},
  {"Actions at exit", 164},
  {"Expunge mails in Garbage mailbox.", 165},
  {"Timeouts", 166},
  {"Mark messages as readed after", 167},
  {"seconds.", 168},
  {"Check active accounts for incoming mail every", 169},
  {"minutes.", 170},
  {"Incoming mail", 171},
  {"Let know the user.", 172},
  {"Outgoing mail", 173},
  {"Wrap text at", 174},
  {"characers.", 175},
  {"Save copy in Outbox mailbox.", 176},
  {"General/Options", 177},
  {"Name", 178},
  {"Type", 179},
  {"Press this button to add a new account to the list.", 180},
  {"_Add", 181},
  {"Press this button to edit the information of the selected account.", 182},
  {"_Edit", 183},
  {"Press this button to remove the selected account of the list.", 184},
  {"_Remove", 185},
  {"Press this button to move up the selected account in the priority list", 186},
  {"_Up", 187},
  {"\
Press this button to move down the selected account in the priority list", 188},
  {"_Down", 189},
  {"General/Accounts", 190},
  {"Paths to prompt to by action", 191},
  {"Save files to disk:", 192},
  {"Get files from disk:", 193},
  {"Use smart path selection.", 194},
  {"General/Paths", 195},
  {"label129", 196},
  {"Press this button to add a plugin to Cronos II.", 197},
  {"Add", 198},
  {"Press this button to remove the selected plugin from Cronos II.", 199},
  {"Remove", 200},
  {"Press this button to configure the selected plugin", 201},
  {"Configure", 202},
  {"Description", 203},
  {"General/Plugins", 204},
  {"Font by occation", 205},
  {"Readed mails:", 206},
  {"Unreaded mails:", 207},
  {"Unreaded mailbox:", 208},
  {"Font to be used for listing mails that have been opened.", 209},
  {"Select font for readed mais", 210},
  {"Pablo was in Paris.", 211},
  {"Font to be used for listing mails that have not been opened.", 212},
  {"Select font for unreaded mails", 213},
  {"Pablo was in Vienna.", 214},
  {"Font to be used for listing mailbox that have unreaded mails in it.", 215},
  {"Select font for unreaded mailbox", 216},
  {"Pablo was in Rome.", 217},
  {"Interface/Fonts", 218},
  {"Images from net", 219},
  {"Download.", 220},
  {"Download if remitent is in address book.", 221},
  {"Do not download.", 222},
  {"Ask for confirmation before downloading.", 223},
  {"Links", 224},
  {"Open using default Gnome browser.", 225},
  {"Open using internal browser.", 226},
  {"Do not open unless is a \"mailto:\" link.", 227},
  {"Ask for confirmation before acting.", 228},
  {"Interpret text/plain symbols.", 229},
  {"Interface/HTML", 230},
  {"Quotes", 231},
  {"Prepend with character", 232},
  {"Highlight with color\t", 233},
  {"Pick a color", 234},
  {"Editor", 235},
  {"Use internal editor.", 236},
  {"Use external editor:", 237},
  {"gnome-edit", 238},
  {"gedit", 239},
  {"gnp", 240},
  {"gvim", 241},
  {"abiword", 242},
  {"Inteface/Composer", 243},
  {"Title format", 244},
  {"%a v.%v - %M (%m messages, %n new)", 245},
  {"%a v.%v - %M", 246},
  {"%a v.%v", 247},
  {"%M - %a %v", 248},
  {"Date format", 249},
  {"%d.%m.%Y %H:%M %z", 250},
  {"%Y.%m.%d %H:%M %z", 251},
  {"%A %d %B %Y %H:%M", 252},
  {"Attachments", 253},
  {"Display", 254},
  {"text/plain", 255},
  {"text/html", 256},
  {"by default.", 257},
  {"Interface/Misc", 258},
  {"Proxy", 259},
  {"FTP Proxy", 260},
  {"HTTP Proxy", 261},
  {"Port", 262},
  {"Copy values.", 263},
  {"Advanced/Misc", 264},
  {"\
This will permanently remove\n\
the selected account.\n\
Do you want to continue?", 265},
  {"Account Setup", 266},
  {"\
Cronos II supports several identities through the usage\n\
of different accounts.\n\
\n\
With this tool you will be able to add new accounts\n\
and edit the information of already existent accounts.\n\
\n\
If you need help you can get it by going to Help the\n\
help menu.", 267},
  {"Identity", 268},
  {"Required information", 269},
  {"Full Name:", 270},
  {"E-Mail Address:", 271},
  {"Optional information", 272},
  {"Organization:", 273},
  {"Reply-To Address:", 274},
  {"Submit Personal Card:", 275},
  {"[TODO]", 276},
  {"\
Please, fill in the information regarding the incoming mail.\n\
If you don't know the protocol the server uses you should ask your\n\
system administrator or your ISP.", 277},
  {"Protocol:", 278},
  {"Server information", 279},
  {"Hostname:", 280},
  {"Port:", 281},
  {"Use Secure Server Layer (SSL).", 282},
  {"Username:", 283},
  {"Authentication", 284},
  {"Authentication method:", 285},
  {"Remember password.", 286},
  {"\
Please, fill in the information regarding the outgoing mail.\n\
If you don't know the protocol your server uses you should ask your\n\
system administrator or your ISP or just use the Sendmail protocol.", 287},
  {"Server Protocol:", 288},
  {"This server requires authentication.", 289},
  {"Account Information", 290},
  {"Name:", 291},
  {"Signature", 292},
  {"Signature file (plain):", 293},
  {"Signature file (HTML):", 294},
  {"Multiple server access options", 295},
  {"Leave messages in the server.", 296},
  {"Remove messages older than", 297},
  {"days.", 298},
  {"Automatically check this account.", 299},
  {"Finished", 300},
  {"\
Congratulations, you have successfully configured\n\
your account for use with Cronos II.\n\
\n\
Press «Finish» to store the new configuration.", 301},
  {"\
The name you entered is\n\
not valid.", 302},
  {"Cronos II", 303},
  {"Compose a new E-Mail", 304},
  {"_E-Mail", 305},
  {"Create a new mailbox", 306},
  {"M_ailbox", 307},
  {"Add a new contact to your address book", 308},
  {"_Contact", 309},
  {"_Check Mail", 310},
  {"Check all accounts for new mail", 311},
  {"All Accounts", 312},
  {"_Send Unsent Mails", 313},
  {"Open the Address Book", 314},
  {"_Address Book", 315},
  {"mmmm, I smell a nice egg coming from the east...", 316},
  {"_From", 317},
  {"_Account", 318},
  {"_To", 319},
  {"_Carbon Copy", 320},
  {"_Blind Carbon Copy", 321},
  {"_Date", 322},
  {"_Subject", 323},
  {"_Priority", 324},
  {"_Mailbox", 325},
  {"_Speed Up", 326},
  {"_Import", 327},
  {"_Export", 328},
  {"Empty _Garbage", 329},
  {"Mess_age", 330},
  {"_Reply", 331},
  {"Reply _all", 332},
  {"_Forward", 333},
  {"Copy selected messages", 334},
  {"_Copy", 335},
  {"Move selected messages", 336},
  {"_Move", 337},
  {"Delete selected messages", 338},
  {"_Delete", 339},
  {"Expunge selected messages", 340},
  {"_Expunge", 341},
  {"Mar_k", 342},
  {"Mark selected message", 343},
  {"_Mark", 344},
  {"Mark selected messages as unreaded", 345},
  {"_Unread", 346},
  {"Mark selected messages as readed", 347},
  {"_Read", 348},
  {"Mark selected messages as replied", 349},
  {"Repl_ied", 350},
  {"Mark selected messages as forwarded", 351},
  {"Select previous message", 352},
  {"_Previous", 353},
  {"Select next message", 354},
  {"_Next", 355},
  {"Try to recover an expunged message", 356},
  {"Reco_very", 357},
  {"_User Manual", 358},
  {"_Quick Tips", 359},
  {"_Getting in Touch", 360},
  {"About _Plugins", 361},
  {"Icon Menu Bar", 362},
  {"Check all accounts for new mail.", 363},
  {"Check", 364},
  {"Send unsent messages from the mail queue", 365},
  {"Send", 366},
  {"Save current message to file.", 367},
  {"Save", 368},
  {"Print current message", 369},
  {"Print", 370},
  {"Delete", 371},
  {"Compose a new message", 372},
  {"Compose", 373},
  {"Reply to the selected message", 374},
  {"Reply", 375},
  {"Reply to all recipients of the selected message", 376},
  {"Reply All", 377},
  {"Forward selected message", 378},
  {"Forward", 379},
  {"Previous", 380},
  {"Next", 381},
  {"Contacts", 382},
  {"Close Cronos II", 383},
  {"Exit", 384},
  {"View Message Pane", 385},
  {"Show the Message Transfer dialog", 386},
  {"\
The mailbox name you\n\
entered is invalid.", 387},
  {"close this dialog", 388},
  {"Mailbox properties", 389},
  {"finished", 390},
  {"Warning", 391},
  {"\
Editing mailbox properties might\n\
result in the lost of all mails in it.", 392},
  {"Type here the name of the new mailbox", 393},
  {"Type:", 394},
  {"Select the type of access you want for this mailbox", 395},
  {"Extra data", 396},
  {"Type here the port where this mailbox is stored", 397},
  {"Type here the hostname where this mailbox is stored", 398},
  {"Password:", 399},
  {"Path:", 400},
  {"Select file", 401},
  {"C2 Addressbook", 402},
  {"Cronos II Addressbook", 403},
  {"_New File", 404},
  {"Open Addressbook file", 405},
  {"close addressbook", 406},
  {"New File", 407},
  {"New", 408},
  {"Open Address Book File", 409},
  {"Open", 410},
  {"Save Address Book File", 411},
  {"Search:", 412},
  {"Groups:", 413},
  {"E-Mail", 414},
  {"Comments", 415},
  {"Address Book vCard", 416},
  {"close card", 417},
  {"_New Mailbox", 418},
  {"Delete selected mailbox", 419},
  {"_Delete Mailbox", 420},
  {"\
Removal of a mailbox will permanently\n\
delete all mail stored in it and any\n\
mailbox depending of it.\n\
\n\
Are you sure you want to delete\n\
this mailbox?", 421},
  {"Remove this Mailbox", 422},
  {"Don't do anything. Close this dialog.", 423},
  {"Make a backup copy", 424},
  {"Archive mails (recommended).", 425},
  {"Message Tranfer", 426},
  {"Finished. Close this dialog.", 427},
  {"Close", 428},
  {"Task list", 429},
  {"Subtasks", 430},
  {"This bar shows how many subtasks there are for the current task", 431},
  {"%v of %u [%P%%]", 432},
  {"Progress of subtask", 433},
  {"%u bytes [%P%%]", 434},
  {"Close this dialog when task completes.", 435},
  {"Automatically close when finished.", 436},
  {"Incorrect Password", 437},
  {"Try this new information", 438},
  {"Account:", 439},
  {"\
The server has rejected the username/password\n\
combination: 'invalid username/password'.\n\
\n\
Provide the correct information for logging in\n\
in the following fields.", 440},
  {"Getting in Touch", 441},
  {"Close this dialog", 442},
  {"\
Getting in Touch:\n\
\n\
There are several ways to get in touch with anyone\n\
from the Cronos II community (users or developers).\n\
\n\
Note that if you want to contact a particular developer for\n\
a special bug-report (or for whatever reason) you should\n\
check the Cronos II homepage for a list of contacts at\n\
_h_t_t_p_:_/_/_c_r_o_n_o_s_I_I_._s_o_u_r_c_e_f_o_r_g_e_._n_e_t_/\n\
\n\
_E_-_M_a_i_l:\n\
\n\
To send a mail to the developers you should write to\n\
our mailing list: _c_r_o_n_o_s_I_I_-_d_e_v_e_l_o_p_e_r_@_l_i_s_t_s_.\
_s_o_u_r_c_e_f_o_r_g_e_._n_e_t.\n\
\n\
To contact other users of Cronos II send mail\n\
to the user's mailing list: _c_r_o_n_o_s_I_I_-_u_s_e_r_s_@_l_i_s_t_s_.\
_s_o_u_r_c_e_f_o_r_g_e_._n_e_t.\n\
\n\
_I_R_C:\n\
\n\
You can chat with both users and developers in the\n\
OpenProjects network by connecting to the server\n\
_i_r_c_._g_n_o_m_e_._o_r_g_:_6_6_6_7 and the channel _#_c_r_o_n_o_s_I_I.", 443},
  {"\
There is no account configured yet.\n\
You need to do this before being\n\
able to compose mails.", 444},
  {"\
Not enough data was filled in,\n\
complete the missing data\n\
and try again.", 445},
  {"Login problem", 446},
  {"Show both icons and text in the buttons", 447},
  {"_Both", 448},
  {"Show only the icons in the buttons", 449},
  {"_Icons", 450},
  {"Show just text in the buttons", 451},
  {"_Text", 452},
  {"Show tooltips of buttons", 453},
  {"_Tooltips", 454},
  {"Inbox", 455},
  {"Outbox", 456},
  {"Queue", 457},
  {"Garbage", 458},
  {"Drafts", 459},
};

int _msg_tbl_length = 459;
