/* Automatically generated by po2tbl.sed from cronosII.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Unable to create structure for Cronos II Db: %s\n", 2},
  {"Unable to update structure for Spool Db: %s\n", 3},
  {"Unable to create structure for Spool Db (1): %s\n", 4},
  {"Unable to create structure for Spool Db (2): %s\n", 5},
  {"Success", 6},
  {"Data exception", 7},
  {"No such message", 8},
  {"Process is busy", 9},
  {"Unknown hostname", 10},
  {"Internal error", 11},
  {"Internal error: Net Object has reached its maximal allocated buffer", 12},
  {"Error connecting to IMAP server.", 13},
  {"Failed to login to IMAP server.", 14},
  {"Error reading from socket on IMAP host %s! Reader thread aborting!\n", 15},
  {"IMAP Server responded with 'BAD': %s\n", 16},
  {"\
A server reply with no tagged ending sent to c2_imap_check_server_reply(): \
%s\n", 17},
  {"This message claims to be multipart, but is broken.", 18},
  {"This message claims to be multipart but it seems to be broken.", 19},
  {"Server does not support APOP", 20},
  {"SMTP server did not respond to our sent messaage in a friendly way", 21},
  {"System Error: Unable to write message to disk for local SMTP command", 22},
  {"Internal C2 Error: Unable to fetch headers in email message", 23},
  {"\
Problem running local SMTP command to send messages -- Check SMTP settings", 24},
  {"Unable to connect to SMTP server", 25},
  {"SMTP server was not friendly on our connect! May not be RFC compliant", 26},
  {"SMTP server did not respond to 'EHLO in a friendly way", 27},
  {"SMTP server did not respond to HELO in a friendly way", 28},
  {"Internal C2 Error: Unable to fetch \"From:\" header in email message", 29},
  {"Internal C2 Error: Unable to fetch \"To:\" header in email message", 30},
  {"SMTP server did not reply to 'MAIL FROM:' in a friendly way", 31},
  {"SMTP server did not reply to 'DATA' in a friendly way", 32},
  {"SMTP server did not reply to 'RCPT TO:' in a friendly way", 33},
  {"Bad syntaxes, quotes aren't closed.\n", 34},
  {"Old configuration found, importing it...", 35},
  {"Creating new configuration due to previous error...", 36},
  {"No previous configuration found, creating new...", 37},
  {"Detecting old configuration...", 38},
  {"Wrong upgrade_database parameters", 39},
  {"Unable to open index file: %s", 40},
  {"Unable to load db: %s", 41},
  {"Unable to move the temporary file to the correct location: %s", 42},
  {"Loading old configuration", 43},
  {"Registering  the new configuration 'Version'", 44},
  {"Success.", 45},
  {"Parsing a mailbox", 46},
  {"Failed.", 47},
  {"Upgrading database", 48},
  {"Registering in the new configuration 'addrbook_init'", 49},
  {"Registering in the new configuration 'empty_garbage'", 50},
  {"Registering in the new configuration 'check_at_start'", 51},
  {"Registering in the new configuration 'use_outbox'", 52},
  {"Registering in the new configuration 'use_persistent_smtp_connection'", 53},
  {"Registering in the new configuration 'check_timeout'", 54},
  {"Registering in the new configuration 'message_size_limit'", 55},
  {"Registering in the new configuration 'net_timeout'", 56},
  {"Registering in the new configuration 'mark_as_read_timeout'", 57},
  {"Registering in the new configuration 'persistent_smtp_port'", 58},
  {"Registering in the new configuration 'prepend_character'", 59},
  {"Registering in the new configuration 'persistent_smtp_host'", 60},
  {"Registering in the new configuration 'color_reply_original_message'", 61},
  {"Registering in the new configuration 'color_misc_body'", 62},
  {"Upgrading mailboxes tree.", 63},
  {"Loading old rc configuration", 64},
  {"Registering in the new configuration 'mime_window'", 65},
  {"Registering in the new configuration 'toolbar'", 66},
  {"Registering in the new configuration 'wm_hpan'", 67},
  {"Registering in the new configuration 'wm_vpan'", 68},
  {"Registering in the new configuration 'wm_clist'", 69},
  {"Registering in the new configuration 'wm_width'", 70},
  {"Registering in the new configuration 'wm_height'", 71},
  {"Registering in the new configuration 'showable_headers:preview'", 72},
  {"Registering in the new configuration 'showable_headers:message'", 73},
  {"Registering in the new configuration 'showable_headers:compose'", 74},
  {"Registering in the new configuration 'showable_headers:save'", 75},
  {"Registering in the new configuration 'showable_headers:print'", 76},
  {"Registering in the new configuration 'font_read'", 77},
  {"Registering in the new configuration 'font_unread'", 78},
  {"Registering in the new configuration 'font_body'", 79},
  {"Registering in the new configuration 'app_title'", 80},
  {"Saving the new configuration", 81},
  {"Creating internal directory structure", 82},
  {"Creating internal file structure", 83},
  {"Configuring Cronos II", 84},
  {"Cronos II Configuration Kit", 85},
  {"Welcome to Cronos II 0.3.0", 86},
  {"\
Since this is the first time you ever used Cronos II 0.3.0\n\
your configuration must be created, in order to be able\n\
to use all of the new functions Cronos II has.\n\
\n\
Through this simple wizard you will be able to finish the\n\
installation of Cronos II in your system.\n\
\n\
To start the process, press the 'Next' button.", 87},
  {"Cronos II 0.3.0", 88},
  {"Installation complete", 89},
  {"\
The installation of Cronos II in your system is complete, you can\n\
now start it by clicking the 'Finish' button or by accessing your\n\
Gnome menu in the Net menu.\n\
\n\
Thanks for choosing Cronos II.\n\
The Cronos II Developers Team.", 90},
  {"\
The configuration wasn't generated.\n\
Quit anyway?", 91},
  {"Compose a new email.", 92},
  {"Set the Account field.", 93},
  {"Account", 94},
  {"Set the To field.", 95},
  {"Address", 96},
  {"Set the CC field.", 97},
  {"Set the BCC field.", 98},
  {"Set the Subject field.", 99},
  {"Subject", 100},
  {"Set the Body.", 101},
  {"Text", 102},
  {"Compose a new email decoding the argument as a mailto: link", 103},
  {"Set the active mailbox at start (default=Inbox)", 104},
  {"Inbox", 105},
  {"Check account for mail.", 106},
  {"Open the main window (default)", 107},
  {"Composer: Untitled", 108},
  {"\
You have choosen to use an external editor instead of the built-in with \
Cronos II.\n\
\n\
Click the button below to run the editor you selected in the Preferences \
dialog.\n\
\n\
Once you finish writting the message in the editor save the file and close \
it.\n\
After that you can manipulate the message using the tools provided in this \
window.\n", 109},
  {"Composer: %s", 110},
  {"Run external editor: %s", 111},
  {"unknown", 112},
  {"The account specified does not exist: %s", 113},
  {"%s (default)", 114},
  {"General", 115},
  {"Interface", 116},
  {"Advanced", 117},
  {"Preferences", 118},
  {"Account Editor", 119},
  {"Post Office Protocol 3 (POP3)", 120},
  {"Internet Message Access Protocol 4 (IMAP)", 121},
  {"SMTP", 122},
  {"Sendmail", 123},
  {"Plain", 124},
  {"APOP", 125},
  {"From", 126},
  {"Date", 127},
  {"Mailbox", 128},
  {"Receive «%s»", 129},
  {"Send «%s»", 130},
  {"Cancel the transfer", 131},
  {"No Inbox mailbox", 132},
  {"Resolving", 133},
  {"Connecting", 134},
  {"Loggining", 135},
  {"Login failed", 136},
  {"Getting mail list", 137},
  {"%u message.", 138},
  {"%u messages.", 139},
  {"Receiving %v of %u", 140},
  {"Synchronizing", 141},
  {"Completed", 142},
  {"Stop all", 143},
  {"Close when finished.", 144},
  {"Send & Receive", 145},
  {"Check", 146},
  {"Check for incoming mails", 147},
  {"Send", 148},
  {"Send outgoing mails", 149},
  {"Search", 150},
  {"Search a message in existent mailboxes", 151},
  {"Save", 152},
  {"Save selected message", 153},
  {"Print", 154},
  {"Print selected message", 155},
  {"Delete", 156},
  {"Delete selected mails", 157},
  {"Copy", 158},
  {"Copy selected mails", 159},
  {"Move", 160},
  {"Move selected mails", 161},
  {"Compose", 162},
  {"Compose a new message", 163},
  {"Reply", 164},
  {"Reply selected message", 165},
  {"Reply All", 166},
  {"Reply selected message to all recipients", 167},
  {"Forward", 168},
  {"Forward selected message", 169},
  {"Previous", 170},
  {"Select previous message", 171},
  {"Next", 172},
  {"Select next message", 173},
  {"Contacts", 174},
  {"Open the Contacts Address Book", 175},
  {"Close", 176},
  {"Close the main window of Cronos II", 177},
  {"Exit", 178},
  {"Exit Cronos II", 179},
  {"\
Cronos II was not able to load the UI, you should check your installation.\n\
Aborting.\n", 180},
  {"Message failed to load: %s.", 181},
  {"Message failed to load.", 182},
  {"The mailbox '%s' couldn't be loaded", 183},
  {"%d messages, %d new.", 184},
  {"You found the Eastern Egg!", 185},
  {"Neat, baby!", 186},
  {"Unable to open about file", 187},
  {"New mailbox", 188},
  {"Unable to create mailbox", 189},
  {"Toolbar Configuration", 190},
  {"Separator", 191},
  {"\
The account name you\n\
selected is already in use.\n\
\n\
Account names need to be unique.\n\
Please choose another one.", 192},
  {"Error", 193},
  {"Close Dialog", 194},
  {"\
The E-Mail address you\n\
entered is not valid.", 195},
  {"\
The account name you\n\
entered is not valid.", 196},
  {"You have not entered a valid hostname.", 197},
  {"\
This will permanently remove\n\
the account from your configuration.\n\
\n\
Are you sure you want this?", 198},
  {"Confirmation", 199},
  {"Information", 200},
  {"Actions at start", 201},
  {"Check for mail in active accounts.", 202},
  {"Load mailboxes", 203},
  {"Actions at exit", 204},
  {"Expunge mails in Garbage mailbox.", 205},
  {"Timeouts", 206},
  {"Mark messages as readed after", 207},
  {"seconds.", 208},
  {"Check active accounts for incoming mail every", 209},
  {"minutes.", 210},
  {"Incoming mail", 211},
  {"Let know the user.", 212},
  {"Outgoing mail", 213},
  {"Save copy in «Sent Items» mailbox.", 214},
  {"Deleting mails", 215},
  {"Store deleted mails in «Trash».", 216},
  {"Ask for confirmation when deleting.", 217},
  {"Archive expunged mails.", 218},
  {"General/Options", 219},
  {"Name", 220},
  {"Type", 221},
  {"Press this button to add a new account to the list.", 222},
  {"_Add", 223},
  {"Press this button to edit the information of the selected account.", 224},
  {"_Edit", 225},
  {"Press this button to remove the selected account of the list.", 226},
  {"_Remove", 227},
  {"Press this button to move up the selected account in the priority list", 228},
  {"_Up", 229},
  {"\
Press this button to move down the selected account in the priority list", 230},
  {"_Down", 231},
  {"General/Accounts", 232},
  {"Paths to prompt to by action", 233},
  {"Save files to disk:", 234},
  {"Get files from disk:", 235},
  {"Use smart path selection.", 236},
  {"General/Paths", 237},
  {"label129", 238},
  {"Press this button to add a plugin to Cronos II.", 239},
  {"Add", 240},
  {"Press this button to remove the selected plugin from Cronos II.", 241},
  {"Remove", 242},
  {"Press this button to configure the selected plugin", 243},
  {"Configure", 244},
  {"Description", 245},
  {"General/Plugins", 246},
  {"Font by occation", 247},
  {"Readed mails:", 248},
  {"Unreaded mails:", 249},
  {"Unreaded mailbox:", 250},
  {"Font to be used for listing mails that have been opened.", 251},
  {"Select font for readed mais", 252},
  {"Pablo was in Paris.", 253},
  {"Font to be used for listing mails that have not been opened.", 254},
  {"Select font for unreaded mails", 255},
  {"Pablo was in Vienna.", 256},
  {"Font to be used for listing mailbox that have unreaded mails in it.", 257},
  {"Select font for unreaded mailbox", 258},
  {"Pablo was in Rome.", 259},
  {"Interface/Fonts", 260},
  {"Images from net", 261},
  {"Download.", 262},
  {"Download if remitent is in address book.", 263},
  {"Do not download.", 264},
  {"Ask for confirmation before downloading.", 265},
  {"Links", 266},
  {"Open using default Gnome browser.", 267},
  {"Open using internal browser.", 268},
  {"Do not open unless is a \"mailto:\" link.", 269},
  {"Ask for confirmation before acting.", 270},
  {"Interpret text/plain symbols.", 271},
  {"Interface/HTML", 272},
  {"Quotes", 273},
  {"Prepend with character", 274},
  {"Highlight with color\t", 275},
  {"Pick a color", 276},
  {"Editor", 277},
  {"Use internal editor.", 278},
  {"Use external editor:", 279},
  {"gnome-edit", 280},
  {"gedit", 281},
  {"gnp", 282},
  {"gvim", 283},
  {"Inteface/Composer", 284},
  {"Title format", 285},
  {"%a v.%v - %M (%m messages, %n new)", 286},
  {"%a v.%v - %M", 287},
  {"%a v.%v", 288},
  {"%M - %a %v", 289},
  {"Date format", 290},
  {"%d.%m.%Y %H:%M %z", 291},
  {"%Y.%m.%d %H:%M %z", 292},
  {"%A %d %B %Y %H:%M", 293},
  {"Attachments", 294},
  {"Display", 295},
  {"text/plain", 296},
  {"text/html", 297},
  {"by default.", 298},
  {"Interface/Misc", 299},
  {"Proxy", 300},
  {"FTP Proxy", 301},
  {"HTTP Proxy", 302},
  {"Port", 303},
  {"Copy values.", 304},
  {"Advanced/Misc", 305},
  {"\
This will permanently remove\n\
the selected account.\n\
Do you want to continue?", 306},
  {"Account Setup", 307},
  {"\
Cronos II supports multiple mail accounts and identities.\n\
\n\
With this tool you will be able to add new accounts\n\
and edit existing accounts.\n\
\n\
Further help is available in the «Help» menu", 308},
  {"Identity", 309},
  {"Required information", 310},
  {"Full Name:", 311},
  {"E-Mail Address:", 312},
  {"\
Name of person or organization which will appear as remitent in outgoing \
messages of this account.", 313},
  {"Optional information", 314},
  {"Organization:", 315},
  {"Reply-To Address:", 316},
  {"\
E-mail address where reply's to mail sent from this account will be sent.", 317},
  {"Submit Personal Card:", 318},
  {"[TODO]", 319},
  {"\
Please, fill in the information regarding the incoming mail.\n\
If you don't know the protocol the server uses you should ask your\n\
system administrator or your ISP.", 320},
  {"Protocol:", 321},
  {"Server information", 322},
  {"Hostname:", 323},
  {"Port:", 324},
  {"Port where Cronos II can access the mail server for your mails", 325},
  {"Mail server where Cronos II will go to fetch your mails", 326},
  {"Use Secure Server Layer (SSL).", 327},
  {"Username:", 328},
  {"Username Cronos II will use to identifies it self at the server", 329},
  {"Authentication", 330},
  {"Authentication method:", 331},
  {"Remember password.", 332},
  {"\
Please, fill in the information regarding the outgoing mail server.\n\
If you don't know the protocol your server uses you should ask your\n\
System Administrator, your ISP or use the Sendmail protocol.", 333},
  {"Server Protocol:", 334},
  {"\
Port where Cronos II can access the Mail Transfer Agent to deliver messages \
from this account", 335},
  {"\
Outgoing mail server where Cronos II will find the Mail Transfer Agent (MTA) \
to deliver messages from this account", 336},
  {"Username Cronos II will use to authenticate it self to the MTA", 337},
  {"Enable this option if your server requires authentication", 338},
  {"This server requires authentication.", 339},
  {"Password", 340},
  {"Options", 341},
  {"Account Information", 342},
  {"Name:", 343},
  {"Unique name that will identify this account", 344},
  {"Signature", 345},
  {"Signature file (plain):", 346},
  {"Signature file (HTML):", 347},
  {"Signature file that will be used when signing messages with no format", 348},
  {"Signature file that will be used when signing messages with HTML format", 349},
  {"Multiple server access options", 350},
  {"\
Enable this if you don't want Cronos II to delete mails in the server after \
fetching them", 351},
  {"Leave messages in the server.", 352},
  {"\
Enable this option if you want Cronos II to delete downloaded messages in \
the server after an specific period of time", 353},
  {"Remove messages older than", 354},
  {"\
Specify the period of time you want Cronos II to keep downloaded messages in \
the server", 355},
  {"days.", 356},
  {"\
Enable this option if you want to include this account in \"All Account\" \
checks", 357},
  {"Automatically check this account.", 358},
  {"Finished", 359},
  {"\
Congratulations, you have successfully configured\n\
your account for use with Cronos II.\n\
\n\
Press «Finish» to store the new configuration.", 360},
  {"\
The name you entered is\n\
not valid.", 361},
  {"Cronos II", 362},
  {"Compose a new E-Mail", 363},
  {"_E-Mail", 364},
  {"Create a new mailbox", 365},
  {"M_ailbox", 366},
  {"Add a new contact to your address book", 367},
  {"_Contact", 368},
  {"_Check Mail", 369},
  {"Check all accounts for new mail", 370},
  {"All Accounts", 371},
  {"_Send Unsent Mails", 372},
  {"Open the Address Book", 373},
  {"_Address Book", 374},
  {"mmmm, I smell a nice egg coming from the east...", 375},
  {"_From", 376},
  {"_Account", 377},
  {"_To", 378},
  {"_Carbon Copy", 379},
  {"_Blind Carbon Copy", 380},
  {"_Date", 381},
  {"_Subject", 382},
  {"_Priority", 383},
  {"_Mailbox", 384},
  {"_Speed Up", 385},
  {"_Import", 386},
  {"_Export", 387},
  {"Empty _Garbage", 388},
  {"Mess_age", 389},
  {"_Reply", 390},
  {"Reply _all", 391},
  {"_Forward", 392},
  {"Copy selected messages", 393},
  {"_Copy", 394},
  {"Move selected messages", 395},
  {"_Move", 396},
  {"Delete selected messages", 397},
  {"_Delete", 398},
  {"Expunge selected messages", 399},
  {"_Expunge", 400},
  {"Mar_k", 401},
  {"Mark selected message as important", 402},
  {"_Important", 403},
  {"Mark selected messages as unreaded", 404},
  {"_Unread", 405},
  {"Mark selected messages as readed", 406},
  {"_Read", 407},
  {"Mark selected messages as replied", 408},
  {"Repl_ied", 409},
  {"Mark selected messages as forwarded", 410},
  {"_Previous", 411},
  {"_Next", 412},
  {"Try to recover an expunged message", 413},
  {"Reco_very", 414},
  {"_User Manual", 415},
  {"_Quick Tips", 416},
  {"_Getting in Touch", 417},
  {"About _Plugins", 418},
  {"Icon Menu Bar", 419},
  {"View Message Pane", 420},
  {"Show the Message Transfer dialog", 421},
  {"\
The mailbox name you\n\
entered is invalid.", 422},
  {"close this dialog", 423},
  {"Mailbox properties", 424},
  {"finished", 425},
  {"Warning", 426},
  {"\
Editing mailbox properties might\n\
result in the lost of all mails in it.", 427},
  {"Type here the name of the new mailbox", 428},
  {"Type:", 429},
  {"Select the type of access you want for this mailbox", 430},
  {"Extra data", 431},
  {"Type here the port where this mailbox is stored", 432},
  {"Type here the hostname where this mailbox is stored", 433},
  {"Password:", 434},
  {"Path:", 435},
  {"Select file", 436},
  {"C2 Addressbook", 437},
  {"Cronos II Addressbook", 438},
  {"_New File", 439},
  {"Open Addressbook file", 440},
  {"close addressbook", 441},
  {"New File", 442},
  {"New", 443},
  {"Open Address Book File", 444},
  {"Open", 445},
  {"Save Address Book File", 446},
  {"Search:", 447},
  {"Groups:", 448},
  {"E-Mail", 449},
  {"Comments", 450},
  {"Address Book vCard", 451},
  {"close card", 452},
  {"_New Mailbox", 453},
  {"Delete selected mailbox", 454},
  {"_Delete Mailbox", 455},
  {"\
Removal of a mailbox will permanently\n\
delete all mail stored in it and any\n\
mailbox depending of it.\n\
\n\
Are you sure you want to delete\n\
this mailbox?", 456},
  {"Remove this Mailbox", 457},
  {"Don't do anything. Close this dialog.", 458},
  {"Make a backup copy", 459},
  {"Archive mails (recommended).", 460},
  {"Incorrect Password", 461},
  {"Try this new information", 462},
  {"Account:", 463},
  {"\
The server has rejected the username/password\n\
combination: ", 464},
  {"\
\n\
Provide the correct information for logging in\n\
in the following fields.", 465},
  {"Getting in Touch", 466},
  {"Close this dialog", 467},
  {"\
Getting in Touch:\n\
\n\
There are several ways to get in touch with anyone\n\
from the Cronos II community (users or developers).\n\
\n\
Note that if you want to contact a particular developer for\n\
a special bug-report (or for whatever reason) you should\n\
check the Cronos II homepage for a list of contacts at\n\
_h_t_t_p_:_/_/_c_r_o_n_o_s_I_I_._s_o_u_r_c_e_f_o_r_g_e_._n_e_t_/\n\
\n\
_E_-_M_a_i_l:\n\
\n\
To send a mail to the developers you should write to\n\
our mailing list: \
_c_r_o_n_o_s_I_I_-_d_e_v_e_l_o_p_e_r_@_l_i_s_t_s_._s_o_u_r_c_e_f_o_r_g_e_._n_\
e_t.\n\
\n\
To contact other users of Cronos II send mail\n\
to the user's mailing list: \
_c_r_o_n_o_s_I_I_-_u_s_e_r_s_@_l_i_s_t_s_._s_o_u_r_c_e_f_o_r_g_e_._n_e_t.\n\
\n\
_I_R_C:\n\
\n\
You can chat with both users and developers in the\n\
OpenProjects network by connecting to the server\n\
_i_r_c_._g_n_o_m_e_._o_r_g_:_6_6_6_7 and the channel _#_c_r_o_n_o_s_I_I.", 468},
  {"\
There is no account configured yet.\n\
You need to do this before being\n\
able to compose mails.", 469},
  {"\
Not enough data was filled in,\n\
complete the missing data\n\
and try again.", 470},
  {"Text _beside icons", 471},
  {"Text _under icons", 472},
  {"_Text only", 473},
  {"_Icons only", 474},
  {"_Tooltips", 475},
  {"_Edit toolbar...", 476},
  {"Toolbar configuration", 477},
  {"Available elements", 478},
  {"label73", 479},
  {"label74", 480},
  {"Current Toolbar", 481},
  {"label75", 482},
  {"label76", 483},
};

int _msg_tbl_length = 483;
