/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("The account name you\n"
              "selected is already in use.\n"
              "\n"
              "Account names need to be unique.\n"
              "Please choose another one.");
gchar *s = N_("Error");
gchar *s = N_("Close Dialog");
gchar *s = N_("The E-Mail address you\n"
              "entered is not valid.");
gchar *s = N_("Error");
gchar *s = N_("Close Dialog");
gchar *s = N_("The account name you\n"
              "entered is not valid.");
gchar *s = N_("Error");
gchar *s = N_("Close Dialog");
gchar *s = N_("You have not entered a valid hostname.");
gchar *s = N_("Error");
gchar *s = N_("This will permanently remove\n"
              "the account from your configuration.\n"
              "\n"
              "Are you sure you want this?");
gchar *s = N_("Confirmation");
gchar *s = N_("Preferences");
gchar *s = N_("Information");
gchar *s = N_("Actions at start");
gchar *s = N_("Check for mail in active accounts.");
gchar *s = N_("Load mailboxes");
gchar *s = N_("Actions at exit");
gchar *s = N_("Expunge mails in Garbage mailbox.");
gchar *s = N_("Timeouts");
gchar *s = N_("Mark messages as readed after");
gchar *s = N_("seconds.");
gchar *s = N_("Check active accounts for incoming mail every");
gchar *s = N_("minutes.");
gchar *s = N_("Incoming mail");
gchar *s = N_("Let know the user.");
gchar *s = N_("Outgoing mail");
gchar *s = N_("Wrap text at");
gchar *s = N_("characers.");
gchar *s = N_("Save copy in Outbox mailbox.");
gchar *s = N_("General/Options");
gchar *s = N_("Name");
gchar *s = N_("E-Mail");
gchar *s = N_("Type");
gchar *s = N_("Press this button to add a new account to the list.");
gchar *s = N_("_Add");
gchar *s = N_("Press this button to edit the information of the selected account.");
gchar *s = N_("_Edit");
gchar *s = N_("Press this button to remove the selected account of the list.");
gchar *s = N_("_Remove");
gchar *s = N_("Press this button to move up the selected account in the priority list");
gchar *s = N_("_Up");
gchar *s = N_("Press this button to move down the selected account in the priority list");
gchar *s = N_("_Down");
gchar *s = N_("General/Accounts");
gchar *s = N_("Paths to prompt to by action");
gchar *s = N_("Save files to disk:");
gchar *s = N_("Get files from disk:");
gchar *s = N_("Use smart path selection.");
gchar *s = N_("General/Paths");
gchar *s = N_("label129");
gchar *s = N_("Press this button to add a plugin to Cronos II.");
gchar *s = N_("Add");
gchar *s = N_("Press this button to remove the selected plugin from Cronos II.");
gchar *s = N_("Remove");
gchar *s = N_("Press this button to configure the selected plugin");
gchar *s = N_("Configure");
gchar *s = N_("Description");
gchar *s = N_("General/Plugins");
gchar *s = N_("Font by occation");
gchar *s = N_("Readed mails:");
gchar *s = N_("Unreaded mails:");
gchar *s = N_("Unreaded mailbox:");
gchar *s = N_("Font to be used for listing mails that have been opened.");
gchar *s = N_("Select font for readed mais");
gchar *s = N_("Pablo was in Paris.");
gchar *s = N_("Font to be used for listing mails that have not been opened.");
gchar *s = N_("Select font for unreaded mails");
gchar *s = N_("Pablo was in Vienna.");
gchar *s = N_("Font to be used for listing mailbox that have unreaded mails in it.");
gchar *s = N_("Select font for unreaded mailbox");
gchar *s = N_("Pablo was in Rome.");
gchar *s = N_("Interface/Fonts");
gchar *s = N_("Images from net");
gchar *s = N_("Download.");
gchar *s = N_("Download if remitent is in address book.");
gchar *s = N_("Do not download.");
gchar *s = N_("Ask for confirmation before downloading.");
gchar *s = N_("Links");
gchar *s = N_("Open using default Gnome browser.");
gchar *s = N_("Open using internal browser.");
gchar *s = N_("Do not open unless is a \"mailto:\" link.");
gchar *s = N_("Ask for confirmation before acting.");
gchar *s = N_("Interpret text/plain symbols.");
gchar *s = N_("Interface/HTML");
gchar *s = N_("Quotes");
gchar *s = N_("Prepend with character");
gchar *s = N_("Highlight with color\t");
gchar *s = N_("Pick a color");
gchar *s = N_("Editor");
gchar *s = N_("Use internal editor.");
gchar *s = N_("Use external editor:");
gchar *s = N_("gnome-edit");
gchar *s = N_("gedit");
gchar *s = N_("gnp");
gchar *s = N_("gvim");
gchar *s = N_("abiword");
gchar *s = N_("gnome-edit");
gchar *s = N_("Inteface/Composer");
gchar *s = N_("Title format");
gchar *s = N_("%a v.%v - %M (%m messages, %n new)");
gchar *s = N_("%a v.%v - %M");
gchar *s = N_("%a v.%v");
gchar *s = N_("%M - %a %v");
gchar *s = N_("%a v.%v - %M (%m messages, %n new)");
gchar *s = N_("Date format");
gchar *s = N_("%d.%m.%Y %H:%M %z");
gchar *s = N_("%Y.%m.%d %H:%M %z");
gchar *s = N_("%A %d %B %Y %H:%M");
gchar *s = N_("%d.%m.%Y %H:%M %z");
gchar *s = N_("Attachments");
gchar *s = N_("Display");
gchar *s = N_("text/plain");
gchar *s = N_("text/html");
gchar *s = N_("by default.");
gchar *s = N_("Interface/Misc");
gchar *s = N_("Proxy");
gchar *s = N_("FTP Proxy");
gchar *s = N_("HTTP Proxy");
gchar *s = N_("Port");
gchar *s = N_("Port");
gchar *s = N_("Copy values.");
gchar *s = N_("Advanced/Misc");
gchar *s = N_("This will permanently remove\n"
              "the selected account.\n"
              "Do you want to continue?");
gchar *s = N_("Confirmation");
gchar *s = N_("Account Editor");
gchar *s = N_("Account Setup");
gchar *s = N_("Cronos II supports several identities through the usage\n"
              "of different accounts.\n"
              "\n"
              "With this tool you will be able to add new accounts\n"
              "and edit the information of already existent accounts.\n"
              "\n"
              "If you need help you can get it by going to Help the\n"
              "help menu.");
gchar *s = N_("Identity");
gchar *s = N_("Required information");
gchar *s = N_("Full Name:");
gchar *s = N_("E-Mail Address:");
gchar *s = N_("Optional information");
gchar *s = N_("Organization:");
gchar *s = N_("Reply-To Address:");
gchar *s = N_("Submit Personal Card:");
gchar *s = N_("[TODO]");
gchar *s = N_("Incoming mail");
gchar *s = N_("Please, fill in the information regarding the incoming mail.\n"
              "If you don't know the protocol the server uses you should ask your\n"
              "system administrator or your ISP.");
gchar *s = N_("Protocol:");
gchar *s = N_("POP3");
gchar *s = N_("IMAP");
gchar *s = N_("Server information");
gchar *s = N_("Hostname:");
gchar *s = N_("Port:");
gchar *s = N_("Use Secure Server Layer (SSL).");
gchar *s = N_("Username:");
gchar *s = N_("Authentication");
gchar *s = N_("Authentication method:");
gchar *s = N_("Password");
gchar *s = N_("APOP");
gchar *s = N_("Remember password.");
gchar *s = N_("Outgoing mail");
gchar *s = N_("Please, fill in the information regarding the outgoing mail.\n"
              "If you don't know the protocol your server uses you should ask your\n"
              "system administrator or your ISP or just use the Sendmail protocol.");
gchar *s = N_("Server Protocol:");
gchar *s = N_("SMTP");
gchar *s = N_("Sendmail");
gchar *s = N_("Server information");
gchar *s = N_("Hostname:");
gchar *s = N_("Port:");
gchar *s = N_("Use Secure Server Layer (SSL).");
gchar *s = N_("Authentication");
gchar *s = N_("Authentication method:");
gchar *s = N_("Password");
gchar *s = N_("Remember password.");
gchar *s = N_("This server requires authentication.");
gchar *s = N_("Options");
gchar *s = N_("Account Information");
gchar *s = N_("Name:");
gchar *s = N_("Signature");
gchar *s = N_("Signature file (plain):");
gchar *s = N_("Signature file (HTML):");
gchar *s = N_("Multiple server access options");
gchar *s = N_("Leave messages in the server.");
gchar *s = N_("Remove messages older than");
gchar *s = N_("days.");
gchar *s = N_("Automatically check this account.");
gchar *s = N_("Finished");
gchar *s = N_("Congratulations, you have successfully configured\n"
              "your account for use with Cronos II.\n"
              "\n"
              "Press «Finish» to store the new configuration.");
gchar *s = N_("The name you entered is\n"
              "not valid.");
gchar *s = N_("Error");
