/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Preferences");
gchar *s = N_("label76");
gchar *s = N_("Through this dialog you will be able to configure Cronos II\n"
              "to behave the way you want it too.\n"
              "\n"
              "When you don't know what a field is for, you can get help by\n"
              "keeping your mouse for a couple of seconds over it, then a\n"
              "little help will pop-up describing what that field is all about.\n"
              "\n"
              "If you need extra help you should get in touch with other users\n"
              "or with the developers.\n"
              "To have the information of how to get in touch you should\n"
              "click on 'Getting in Touch' in the Help menu of the main window.");
gchar *s = N_("General");
gchar *s = N_("Check for mail every");
gchar *s = N_("minutes.");
gchar *s = N_("Wait");
gchar *s = N_("seconds before marking a mail as readed.");
gchar *s = N_("Prepend");
gchar *s = N_("> \n"
              "::> \n"
              "# \n"
              "Quote# \n"
              "");
gchar *s = N_("> ");
gchar *s = N_("to each line when replying a message.");
gchar *s = N_("Empty the Garbage mailbox on exit.");
gchar *s = N_("Store a copy of outgoing messages in the Outbox mailbox.");
gchar *s = N_("Check for mail at start up.");
gchar *s = N_("Default MIME part to display:");
gchar *s = N_("Options");
gchar *s = N_("Account");
gchar *s = N_("Name");
gchar *s = N_("E-Mail");
gchar *s = N_("Click this button to create a new account");
gchar *s = N_("_Add");
gchar *s = N_("Click this button to edit the information of the current selected mailbox");
gchar *s = N_("_Modify");
gchar *s = N_("Click this button to remove the current selected account");
gchar *s = N_("_Remove");
gchar *s = N_("Click this button to move up the current selected account in the priority order");
gchar *s = N_("_Up");
gchar *s = N_("Click this button to move down the current selected account in the priority order");
gchar *s = N_("_Down");
gchar *s = N_("Accounts");
gchar *s = N_("Application's Title");
gchar *s = N_("Conversion characters:\n"
              "%a: Application's name (Cronos II);\n"
              "%v: Application's version;\n"
              "%m: Number of mails in current mailbox;\n"
              "%n: Number of unreaded mails in current mailbox;\n"
              "%M: Name of selected mailbox.");
gchar *s = N_("Show toolbar with");
gchar *s = N_("Icons only\n"
              "Text only\n"
              "Icons & Text\n"
              "");
gchar *s = N_("Date format:");
gchar *s = N_("%d.%m.%Y %H:%M %z\n"
              "%Y.%m.%d %H:%M %z\n"
              "%A %d %B %Y %H:%M\n"
              "");
gchar *s = N_("Date format to be shown in strftime format. Check man:strfrim(3) for help.");
gchar *s = N_("%d.%m.%Y %H:%M %z");
gchar *s = N_("Interface");
gchar *s = N_("Message Body:");
gchar *s = N_("Unreaded Message:");
gchar *s = N_("Readed Message:");
gchar *s = N_("Pick a Font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Pick a Font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Pick a Font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Fonts");
gchar *s = N_("Replying and Forwarding");
gchar *s = N_("Pick a color");
gchar *s = N_("Original message:");
gchar *s = N_("Message Displaying");
gchar *s = N_("Default background color:");
gchar *s = N_("Pick a color");
gchar *s = N_("Default foreground color:");
gchar *s = N_("Pick a color");
gchar *s = N_("Use document specified colors.\n"
              "Always use my colors.\n"
              "");
gchar *s = N_("Colors");
gchar *s = N_("Default directory for saving files");
gchar *s = N_("Browse...");
gchar *s = N_("Default directory for downloading files");
gchar *s = N_("Browse...");
gchar *s = N_("Default directory for getting files");
gchar *s = N_("Browse...");
gchar *s = N_("Always prompt for this directories.");
gchar *s = N_("Paths");
gchar *s = N_("Proxy");
gchar *s = N_("HTTP Proxy:");
gchar *s = N_("Port:");
gchar *s = N_("FTP Proxy:");
gchar *s = N_("Port:");
gchar *s = N_("Use persistent SMTP connection:");
gchar *s = N_("Port:");
gchar *s = N_("Use internal browser for following links.");
gchar *s = N_("Advanced");
gchar *s = N_("Cronos II : Preferences : Accounts");
gchar *s = N_("Account Options");
gchar *s = N_("This wizard will help you with the configuration of your\n"
              "accounts for use with Cronos II.\n"
              "\n"
              "Each account is a separated entity for Cronos II, this will\n"
              "let you define different persons or entities and manage\n"
              "all of your emails accounts as if it where with separated\n"
              "users.");
gchar *s = N_("Basic Information");
gchar *s = N_("Write here the name which with you want to identify this account. Note that this is just for internal use.");
gchar *s = N_("This is the name that will be sent in outgoing messages in the \"From:\" field.");
gchar *s = N_("Account Name:");
gchar *s = N_("Person Name:");
gchar *s = N_("Include this account in general account checks.");
gchar *s = N_("Organization:");
gchar *s = N_("E-Mail Address:");
gchar *s = N_("Reply-To Address:");
gchar *s = N_("Attach Address Book Card with outgoing mails");
gchar *s = N_("Select Card");
gchar *s = N_("Protocol Information");
gchar *s = N_("Protocol data");
gchar *s = N_("Port:");
gchar *s = N_("Username:");
gchar *s = N_("Password:");
gchar *s = N_("Hostname:");
gchar *s = N_("Leave downloaded messages in server.");
gchar *s = N_("SMTP Options");
gchar *s = N_("Remote SMTP Server.");
gchar *s = N_("Local sendmail program (MUA).");
gchar *s = N_("Set Information");
gchar *s = N_("Signature");
gchar *s = N_("Type of signature:");
gchar *s = N_("Signature");
gchar *s = N_("Automatically append this signature to outgoing messages.");
gchar *s = N_("Account Options");
gchar *s = N_("Congratulations! You have successfully created an account to\n"
              "be use with Cronos II.\n"
              "\n"
              "Click the 'Finish' button to save this new account.");
gchar *s = N_("The Account Name you choosed\n"
              "is already being used by other\n"
              "account.\n"
              "\n"
              "The account names can not be\n"
              "repited.");
gchar *s = N_("Error");
gchar *s = N_("The E-Mail address you\n"
              "entered is not valid.");
gchar *s = N_("Error");
gchar *s = N_("SMTP Server Information");
gchar *s = N_("Provide here the information for the\n"
              "SMTP server for this account.");
gchar *s = N_("\n"
              "localhost\n"
              "");
gchar *s = N_("Hostname:");
gchar *s = N_("Port:");
gchar *s = N_("This server requires authentication");
gchar *s = N_("Authentication Information");
gchar *s = N_("Username:");
gchar *s = N_("Password:");
gchar *s = N_("The Account name you\n"
              "entered is not valid.");
gchar *s = N_("Error");
gchar *s = N_("You selected that you want to\n"
              "use a remote SMTP server for\n"
              "outgoing mails of this account,\n"
              "but you didn't set the information\n"
              "to contact it.\n"
              "\n"
              "Click the button labeled\n"
              "'Set Information' to enter the\n"
              "needed data.");
gchar *s = N_("Error");
gchar *s = N_("You didn't entered a valid hostname.");
gchar *s = N_("Error");
gchar *s = N_("You didn't entered a valid username.");
gchar *s = N_("Error");
gchar *s = N_("This will permanently remove\n"
              "the account from your configuration.\n"
              "\n"
              "Are you sure you want this?");
gchar *s = N_("Confirmation");
