/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Configuration Dialog. Select the area you would like to configure.");
gchar *s = N_("Preferences");
gchar *s = N_("OK");
gchar *s = N_("Apply");
gchar *s = N_("Abort");
gchar *s = N_("Select from these.");
gchar *s = N_("label76");
gchar *s = N_("This dialog is here to help you configure CronosII .\n"
              "You select the area(s) you would like to configure from\n"
              "the menu to the left.\n"
              "Mouse-over help is available for most functions. \n"
              "(Just move the mouse over the area you want to find out about.)\n"
              "\n"
              "Beyond that there should be a User Manual available from the Help Menu\n"
              " and on the Web site. http://cronosii.sourceforge.net \n"
              "If you are still in need of help you should get in touch with other users\n"
              "or with the developers. \n"
              "Click on 'Getting in Touch' in the Help menu of the main window.");
gchar *s = N_("General");
gchar *s = N_("Check for mail every");
gchar *s = N_("Enter a time (in minutes) here.");
gchar *s = N_("minutes.");
gchar *s = N_("Wait");
gchar *s = N_("Enter the number of seconds to wait before marking a message as having being read.");
gchar *s = N_("seconds before marking a mail as read");
gchar *s = N_("Wrap outgoing text at");
gchar *s = N_("Enter the column numbers (width) for your page.");
gchar *s = N_("characters.");
gchar *s = N_("Prepend");
gchar *s = N_("> ");
gchar *s = N_("::> ");
gchar *s = N_("# ");
gchar *s = N_("Quote# ");
gchar *s = N_("> ");
gchar *s = N_("to each line when replying a message.");
gchar *s = N_("Empty the Garbage mailbox on exit.");
gchar *s = N_("Store a copy of outgoing messages in the Outbox mailbox.");
gchar *s = N_("Check for mail at start up.");
gchar *s = N_("Message Transfer mode:");
gchar *s = N_("This is the mode that will be used when transfering messages. Multithread means that the transfering will start right when it is needed (all transfers at once). Monothread means that the transfering will be done one by one.");
gchar *s = N_("Default MIME part to display:");
gchar *s = N_("Options");
gchar *s = N_("Account");
gchar *s = N_("Name");
gchar *s = N_("E-Mail");
gchar *s = N_("Click this button to create a new account");
gchar *s = N_("_Add");
gchar *s = N_("Click this button to edit the currently selected mailbox");
gchar *s = N_("_Modify");
gchar *s = N_("Click this button to remove the currently selected account");
gchar *s = N_("_Remove");
gchar *s = N_("Click this button to movethe currently selected account up the priority order");
gchar *s = N_("_Up");
gchar *s = N_("Click this button to move the currentlu selected account down the priority order.");
gchar *s = N_("_Down");
gchar *s = N_("Accounts");
gchar *s = N_("Application's Title");
gchar *s = N_("Configure the Window Managers Title for the Main Window");
gchar *s = N_("Conversion characters:\n"
              "%a: Application's name (Cronos II);\n"
              "%v: Application's version;\n"
              "%m: Total mail in current mailbox;\n"
              "%n: Unread mail in the current mailbox;\n"
              "%M: Name of selected mailbox.");
gchar *s = N_("Show toolbar with");
gchar *s = N_("Icons only");
gchar *s = N_("Text only");
gchar *s = N_("Icons & Text");
gchar *s = N_("Date format:");
gchar *s = N_("%d.%m.%Y %H:%M %z");
gchar *s = N_("%Y.%m.%d %H:%M %z");
gchar *s = N_("%A %d %B %Y %H:%M");
gchar *s = N_("Date format to be shown in strftime format. Check man:strfrim(3) for help.");
gchar *s = N_("%d.%m.%Y %H:%M %z");
gchar *s = N_("Interface");
gchar *s = N_("Message Body:");
gchar *s = N_("Unread Message:");
gchar *s = N_("Read Message:");
gchar *s = N_("Pick a Font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Pick a Font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Pick a Font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Fonts");
gchar *s = N_("Replying and Forwarding");
gchar *s = N_("Pick a color");
gchar *s = N_("Original message:");
gchar *s = N_("Message Displaying");
gchar *s = N_("Default background color:");
gchar *s = N_("Pick a color");
gchar *s = N_("Default foreground color:");
gchar *s = N_("Pick a color");
gchar *s = N_("Use document specified colors.");
gchar *s = N_("Always use my colors.");
gchar *s = N_("Colors");
gchar *s = N_("Default directory for saving files");
gchar *s = N_("Browse...");
gchar *s = N_("Default destination directory for downloaded files.");
gchar *s = N_("Choose a directory to download files to.");
gchar *s = N_("Browse...");
gchar *s = N_("Default directory for getting files");
gchar *s = N_("Browse...");
gchar *s = N_("Always prompt for this directories.");
gchar *s = N_("Paths");
gchar *s = N_("Proxy");
gchar *s = N_("HTTP Proxy:");
gchar *s = N_("Port:");
gchar *s = N_("FTP Proxy:");
gchar *s = N_("Port:");
gchar *s = N_("Use persistent SMTP connection:");
gchar *s = N_("Port:");
gchar *s = N_("Use internal browser for following links.");
gchar *s = N_("Advanced");
gchar *s = N_("Cronos II : Preferences : Accounts");
gchar *s = N_("Account Configuration Druid");
gchar *s = N_("Account Options");
gchar *s = N_("This Druid (wizard) will help you with the configuration of your mail\n"
              "accounts for use with Cronos II.\n"
              "CronosII allows you to have many seperate accounts of different types \n"
              "and from different sources. As far as CronosII is concerned each account \n"
              "is a seperate entity.\n"
              "This is where you manage all of those accounts.");
gchar *s = N_("Basic Information");
gchar *s = N_("This is where you tell CronosII the name that You wish to refer to this account as. (It's between you and CronosII)");
gchar *s = N_("This is the name that will be sent in outgoing messages in the \"From:\" field.");
gchar *s = N_("Account Name:");
gchar *s = N_("Person Name:");
gchar *s = N_("Select this to add this account to the check all list. (defaults)");
gchar *s = N_("Include this account in general account checks.");
gchar *s = N_("The address that gets selected when they \"reply\" to you. This can be the same as the above E-mail address.");
gchar *s = N_("Your E-mail Address");
gchar *s = N_("Organization:");
gchar *s = N_("The name of your organization.");
gchar *s = N_("E-Mail Address:");
gchar *s = N_("Reply-To Address:");
gchar *s = N_("Attach an address book card to all mail from this account.");
gchar *s = N_("Attach Address Book Card with outgoing mails");
gchar *s = N_("Select the Vcard you would like to include with all mail from this account.");
gchar *s = N_("Select Card");
gchar *s = N_("Protocol Information");
gchar *s = N_("Choose a mail protocol for this account. The default is pop3 (leave it at this if you are not sure)");
gchar *s = N_("pop3");
gchar *s = N_("smtp");
gchar *s = N_("mime");
gchar *s = N_("Protocol data");
gchar *s = N_("The Hostname of the Mail Server.");
gchar *s = N_("Port:");
gchar *s = N_("Username:");
gchar *s = N_("Your User Name at this Mail Server");
gchar *s = N_("Password:");
gchar *s = N_("Your Password at this Mail Server");
gchar *s = N_("Hostname:");
gchar *s = N_("Select this to leave mail on the pop3 server. (You still get a full copy)");
gchar *s = N_("Leave downloaded messages in server.");
gchar *s = N_("SMTP Options");
gchar *s = N_("Select this to configure the information needed by outgoing mail for this account.");
gchar *s = N_("Remote SMTP Server.");
gchar *s = N_("Select your local Unix  style mail spool.");
gchar *s = N_("Local sendmail program (MUA).");
gchar *s = N_("This information is correct.");
gchar *s = N_("Set Information");
gchar *s = N_("Your Username for this SMTP server.");
gchar *s = N_("Your password for this server.");
gchar *s = N_("the server port at the server. The default is 25. Your provider and / or admin. should know this otherwise.");
gchar *s = N_("The address of the remote SMTP server. This often begins with mail. .");
gchar *s = N_("mail.");
gchar *s = N_("Signature");
gchar *s = N_("Type of signature:");
gchar *s = N_("Choose how you signature is generated here.");
gchar *s = N_("Signature");
gchar *s = N_("Type you signature into here.");
gchar *s = N_("Select this to add it automatically to each message from this account.");
gchar *s = N_("Automatically append this signature to outgoing messages.");
gchar *s = N_("Account Options");
gchar *s = N_("Congratulations! You have successfully created an account to\n"
              "be use with Cronos II.\n"
              "\n"
              "Click the 'Finish' button to save this new account.");
gchar *s = N_("Error Message");
gchar *s = N_("Account Names must be unique.\n"
              "\n"
              "The chosen Account Name is being used by another account.\n"
              "");
gchar *s = N_("Error");
gchar *s = N_("OK");
gchar *s = N_("An Error message");
gchar *s = N_("The entered E-Mail address is not valid.");
gchar *s = N_("Error");
gchar *s = N_("You will need to enter a properly constructed email address.");
gchar *s = N_("Your service provider or your System Administrator will have this information.");
gchar *s = N_("SMTP Server Information");
gchar *s = N_("Done");
gchar *s = N_("Maybe I should read the manual.");
gchar *s = N_("Please provide the connect information for the\n"
              "SMTP server for this account.");
gchar *s = N_("localhost");
gchar *s = N_("Enter the Hostname of the Server here.");
gchar *s = N_("Hostname:");
gchar *s = N_("Port:");
gchar *s = N_("Enter the port number for that mail server here.");
gchar *s = N_("This server need me to verify myself.");
gchar *s = N_("This server requires authentication");
gchar *s = N_("Authentication Information");
gchar *s = N_("Username:");
gchar *s = N_("Password:");
gchar *s = N_("You Username at this SMTP server.");
gchar *s = N_("Your current Password at this SMTP server");
gchar *s = N_("The entered Account name is not valid.");
gchar *s = N_("Error");
gchar *s = N_("Error. External Server specified but not configured !");
gchar *s = N_("You have chosen to use an external SMTP mail handler ( to send this accounts mail).\n"
              "The information required to connect to that server is not correctly configured.\n"
              "Click the button labeled 'Set Information' to enter the needed data.");
gchar *s = N_("Error");
gchar *s = N_("OK. I will fix this before I use this account.");
gchar *s = N_("Invalid Hostname.\n"
              "Please correct this.");
gchar *s = N_("Error");
gchar *s = N_("Please Check and re-enter this information");
gchar *s = N_("Please check and re-enter this information");
gchar *s = N_("You need to enter a valid Username.");
gchar *s = N_("Error");
gchar *s = N_("This will permanently remove\n"
              "the account, and any contents from your configuration.\n"
              "\n"
              "Are you sure you want this?");
gchar *s = N_("Confirmation");
gchar *s = N_("Your Sure about this then?");
gchar *s = N_("Your not really sure yet.");
