/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Cronos II");
gchar *s = N_("Compose a new E-Mail");
gchar *s = N_("_E-Mail");
gchar *s = N_("Create a new mailbox");
gchar *s = N_("M_ailbox...");
gchar *s = N_("Add a new contact to your address book");
gchar *s = N_("_Contact...");
gchar *s = N_("Open a new main window");
gchar *s = N_("_Window");
gchar *s = N_("_Check Mail");
gchar *s = N_("Check all accounts for new mail");
gchar *s = N_("All Accounts");
gchar *s = N_("_Send unsent mails");
gchar *s = N_("Open the Address Book");
gchar *s = N_("_Address Book");
gchar *s = N_("_Save...");
gchar *s = N_("_Print...");
gchar *s = N_("mmmm, I smell a nice egg coming from the east...");
gchar *s = N_("_Toolbar");
gchar *s = N_("_Mailboxes List");
gchar *s = N_("Mail _Preview");
gchar *s = N_("_Headers");
gchar *s = N_("_Network Traffic");
gchar *s = N_("Mail _Source");
gchar *s = N_("Network _Traffic");
gchar *s = N_("Send & Re_ceive");
gchar *s = N_("_Mailbox");
gchar *s = N_("_Speed Up...");
gchar *s = N_("_Import...");
gchar *s = N_("_Export...");
gchar *s = N_("Empty _Garbage");
gchar *s = N_("Mess_age");
gchar *s = N_("_Reply");
gchar *s = N_("Reply to _all");
gchar *s = N_("_Forward");
gchar *s = N_("Copy selected messages");
gchar *s = N_("_Copy...");
gchar *s = N_("Move selected messages");
gchar *s = N_("_Move...");
gchar *s = N_("Delete selected messages");
gchar *s = N_("_Delete");
gchar *s = N_("Expunge selected messages");
gchar *s = N_("_Expunge");
gchar *s = N_("Mar_k");
gchar *s = N_("Mark selected message as important");
gchar *s = N_("_Important");
gchar *s = N_("Mark selected messages as unreaded");
gchar *s = N_("_Unreaded");
gchar *s = N_("Mark selected messages as readed");
gchar *s = N_("_Readed");
gchar *s = N_("Mark selected messages as replied");
gchar *s = N_("Repl_ied");
gchar *s = N_("Mark selected messages as forwarded");
gchar *s = N_("_Forwarded");
gchar *s = N_("Select previous message");
gchar *s = N_("_Previous");
gchar *s = N_("Select next message");
gchar *s = N_("_Next");
gchar *s = N_("Try to recover an expunged message");
gchar *s = N_("Reco_ver");
gchar *s = N_("F_ilters");
gchar *s = N_("_Rule Manager...");
gchar *s = N_("_Apply rule to selected mailbox");
gchar *s = N_("_Features");
gchar *s = N_("_Download new features from Internet...");
gchar *s = N_("_User Manual");
gchar *s = N_("_Quick Tips...");
gchar *s = N_("_Getting in Touch...");
gchar *s = N_("_Release Information...");
gchar *s = N_("About _Plugins...");
gchar *s = N_("_Filters:");
gchar *s = N_("From");
gchar *s = N_("To");
gchar *s = N_("Date");
gchar *s = N_("Account");
gchar *s = N_("Subject");
gchar *s = N_("Body");
gchar *s = N_("contains");
gchar *s = N_("is equal to");
gchar *s = N_("Cas_e sensitive");
gchar *s = N_("Show the Message Transfer dialog");
gchar *s = N_("The mailbox name you\n"
              "entered is invalid.");
gchar *s = N_("Error");
gchar *s = N_("close this dialog");
gchar *s = N_("Mailbox properties");
gchar *s = N_("finished");
gchar *s = N_("Warning");
gchar *s = N_("Editing mailboxes properties might\n"
              "result in the lost of all mails in it.");
gchar *s = N_("Basic information");
gchar *s = N_("Type here the name of the new mailbox");
gchar *s = N_("_Type:");
gchar *s = N_("_Name:");
gchar *s = N_("Select the type of access you want for this mailbox");
gchar *s = N_("Parent");
gchar *s = N_("Extra information");
gchar *s = N_("_Path:");
gchar *s = N_("Select file");
gchar *s = N_("C2 Addressbook");
gchar *s = N_("Cronos II Addressbook");
gchar *s = N_("_New File");
gchar *s = N_("Open Addressbook file");
gchar *s = N_("close addressbook");
gchar *s = N_("New File");
gchar *s = N_("New");
gchar *s = N_("Open Address Book File");
gchar *s = N_("Open");
gchar *s = N_("Save Address Book File");
gchar *s = N_("Save");
gchar *s = N_("Search:");
gchar *s = N_("Groups:");
gchar *s = N_("Name");
gchar *s = N_("E-Mail");
gchar *s = N_("Comments");
gchar *s = N_("Address Book vCard");
gchar *s = N_("close card");
gchar *s = N_("Create a new mailbox");
gchar *s = N_("_New Mailbox");
gchar *s = N_("Delete selected mailbox");
gchar *s = N_("_Delete Mailbox");
gchar *s = N_("Download new mails to this mailbox");
gchar *s = N_("Use as _Inbox");
gchar *s = N_("Store unsent outgoing mails in this mailbox");
gchar *s = N_("Use as _Outbox");
gchar *s = N_("Store sent mails in this mailbox");
gchar *s = N_("Use as _Sent Items");
gchar *s = N_("Store deleted mails in this mailbox");
gchar *s = N_("Use as _Trash");
gchar *s = N_("Store unfinished outgoing mails in this mailbox");
gchar *s = N_("Use as _Drafts");
gchar *s = N_("Removal of a mailbox will permanently\n"
              "delete all mail stored in it and any\n"
              "mailbox depending of it.\n"
              "\n"
              "Are you sure you want to delete\n"
              "this mailbox?");
gchar *s = N_("Confirmation");
gchar *s = N_("Remove this Mailbox");
gchar *s = N_("Don't do anything. Close this dialog.");
gchar *s = N_("Make a backup copy");
gchar *s = N_("Archive mails (recommended).");
gchar *s = N_("Incorrect Password");
gchar *s = N_("Try this new information");
gchar *s = N_("Close");
gchar *s = N_("Password:");
gchar *s = N_("Username:");
gchar *s = N_("Account:");
gchar *s = N_("The server has rejected the username/password\n"
              "combination: ");
gchar *s = N_("\n"
              "Provide the correct information for logging in\n"
              "in the following fields.");
gchar *s = N_("Getting in Touch");
gchar *s = N_("Close this dialog");
gchar *s = N_("There is no account configured yet.\n"
              "You need to do this before being\n"
              "able to compose mails.");
gchar *s = N_("Error");
gchar *s = N_("Preferences");
gchar *s = N_("You found the Eastern Egg!");
gchar *s = N_("Neat, baby!");
gchar *s = N_("Not enough data was filled in,\n"
              "complete the missing data\n"
              "and try again.");
gchar *s = N_("Error");
gchar *s = N_("Text _beside icons");
gchar *s = N_("Text _under icons");
gchar *s = N_("_Text only");
gchar *s = N_("_Icons only");
gchar *s = N_("_Tooltips");
gchar *s = N_("_Edit toolbar...");
gchar *s = N_("Toolbar configuration");
gchar *s = N_("Available elements");
gchar *s = N_("label73");
gchar *s = N_("label74");
gchar *s = N_("Current Toolbar");
gchar *s = N_("label75");
gchar *s = N_("label76");
gchar *s = N_("There is a file by that name already.\n"
              "\n"
              "Do you want to overwrite it?");
gchar *s = N_("Confirmation");
gchar *s = N_("Confirmation");
gchar *s = N_("Are you sure you want to\n"
              "delete the selected mails?");
gchar *s = N_("Do not ask again.");
gchar *s = N_("Are you sure you want to\n"
              "expunge the selected mails?");
gchar *s = N_("Confirmation");
gchar *s = N_("Release Information");
gchar *s = N_("Welcome");
gchar *s = N_("Known Bugs");
gchar *s = N_("Missing Features");
gchar *s = N_("Show this dialog at start.");
gchar *s = N_("Select Mailbox");
gchar *s = N_("You selected a directory.");
gchar *s = N_("Error");
gchar *s = N_("About");
gchar *s = N_("Web Site");
gchar *s = N_("Attachments Tool");
gchar *s = N_("Save selected attachments to disk");
gchar *s = N_("Mail Source");
gchar *s = N_("Add features");
gchar *s = N_("Add Features");
gchar *s = N_("Cronos II is prepared to add new cool features in any time you want.\n"
              "\n"
              "What follow is a list of all available features of Cronos II that you can download from the Internet and install in a quick and easy way.");
gchar *s = N_("New Features available");
gchar *s = N_("Downloading...");
gchar *s = N_("Rule Manager");
gchar *s = N_("_Add rule");
gchar *s = N_("_Edit rule");
gchar *s = N_("_Remove rule");
gchar *s = N_("Rule Editor");
gchar *s = N_("_Open Message");
gchar *s = N_("_Reply");
gchar *s = N_("Reply to _all");
gchar *s = N_("_Forward");
gchar *s = N_("_Delete");
gchar *s = N_("_Expunge...");
gchar *s = N_("_Mark");
gchar *s = N_("_Important");
gchar *s = N_("_Unreaded");
gchar *s = N_("_Readed");
gchar *s = N_("Repl_ied");
gchar *s = N_("_Forwarded");
gchar *s = N_("_Copy...");
gchar *s = N_("_Move...");
gchar *s = N_("_Previous");
gchar *s = N_("_Next");
gchar *s = N_("_Save...");
gchar *s = N_("_Print...");
