/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Cronos II");
gchar *s = N_("_E-Mail");
gchar *s = N_("M_ailbox");
gchar *s = N_("_Contact");
gchar *s = N_("_Check Mail");
gchar *s = N_("All Accounts");
gchar *s = N_("Persistent _SMTP");
gchar *s = N_("_Connect");
gchar *s = N_("_Disconnect");
gchar *s = N_("_Send Unsent Mails");
gchar *s = N_("_Address Book");
gchar *s = N_("_From");
gchar *s = N_("_Account");
gchar *s = N_("_To");
gchar *s = N_("_Carbon Copy");
gchar *s = N_("_Blind Carbon Copy");
gchar *s = N_("_Date");
gchar *s = N_("_Subject");
gchar *s = N_("_Priority");
gchar *s = N_("_Mailbox");
gchar *s = N_("_Speed Up");
gchar *s = N_("_Import");
gchar *s = N_("_Export");
gchar *s = N_("Mess_age");
gchar *s = N_("_Reply");
gchar *s = N_("Reply _all");
gchar *s = N_("_Forward");
gchar *s = N_("Copy selected messages");
gchar *s = N_("_Copy");
gchar *s = N_("Move selected messages");
gchar *s = N_("_Move");
gchar *s = N_("Delete selected messages");
gchar *s = N_("_Delete");
gchar *s = N_("Expunge selected messages");
gchar *s = N_("_Expunge");
gchar *s = N_("Mar_k");
gchar *s = N_("Mark selected message");
gchar *s = N_("_Mark");
gchar *s = N_("Mark selected messages as unreaded");
gchar *s = N_("_Unread");
gchar *s = N_("Mark selected messages as readed");
gchar *s = N_("_Read");
gchar *s = N_("Mark selected messages as replied");
gchar *s = N_("Repl_ied");
gchar *s = N_("Mark selected messages as forwarded");
gchar *s = N_("_Forward");
gchar *s = N_("Select previous message");
gchar *s = N_("_Previous");
gchar *s = N_("Select next message");
gchar *s = N_("_Next");
gchar *s = N_("_User Manual");
gchar *s = N_("_Quick Tips");
gchar *s = N_("Check all accounts for new mails");
gchar *s = N_("Check");
gchar *s = N_("Send unset messages");
gchar *s = N_("Send");
gchar *s = N_("Save current message");
gchar *s = N_("Save");
gchar *s = N_("Print current message");
gchar *s = N_("Print");
gchar *s = N_("Delete selected messages");
gchar *s = N_("Delete");
gchar *s = N_("Compose a new message");
gchar *s = N_("Compose");
gchar *s = N_("Reply selected message");
gchar *s = N_("Reply");
gchar *s = N_("Reply to all recipients of the selected message");
gchar *s = N_("Reply All");
gchar *s = N_("Forward selected message");
gchar *s = N_("Forward");
gchar *s = N_("Select previous message");
gchar *s = N_("Previous");
gchar *s = N_("Select next message");
gchar *s = N_("Next");
gchar *s = N_("Contacts");
gchar *s = N_("Exit");
gchar *s = N_("label7");
gchar *s = N_("Show the Checking Window.");
gchar *s = N_("Mailbox Options");
gchar *s = N_("Name:");
gchar *s = N_("Type");
gchar *s = N_("\n"
              "");
gchar *s = N_("Extra data");
gchar *s = N_("Port:");
gchar *s = N_("localhost");
gchar *s = N_("Host:");
gchar *s = N_("User:");
gchar *s = N_("Pass:");
gchar *s = N_("Db:");
gchar *s = N_("That mailbox name\n"
              "is already taken.");
gchar *s = N_("Error");
gchar *s = N_("Cronos II : Checking");
gchar *s = N_("Checking account %s %v of %u");
gchar *s = N_("Getting E-Mail %v of %u (%p%%)");
gchar *s = N_("This progress bar indicates the progress of the fetch of the current message.");
gchar *s = N_("%P %%");
gchar *s = N_("Account");
gchar *s = N_("Description");
gchar *s = N_("2000-2001 Pablo Fernández Navarro");
gchar *s = N_("Cronos II is a fast, light, user friendly and powerful mail client for the Gnome Desktop.\n"
              "It has an extended and intuitive interface which will make life for novice easier without taking out the power to the gurus.\n"
              "\n"
              " \n"
              "You can find the website of Cronos II at:\n"
              "http://cronosII.sourceforge.net");
gchar *s = N_("Cronos II");
gchar *s = N_("_New File");
gchar *s = N_("New File");
gchar *s = N_("New");
gchar *s = N_("Open File");
gchar *s = N_("Open");
gchar *s = N_("Save File");
gchar *s = N_("Save");
gchar *s = N_("Search:");
gchar *s = N_("Groups:");
gchar *s = N_("Name");
gchar *s = N_("E-Mail");
gchar *s = N_("Comments");
gchar *s = N_("Address Book vCard");
gchar *s = N_("Preferences");
gchar *s = N_("Check for mail every");
gchar *s = N_("minutes.");
gchar *s = N_("Wait");
gchar *s = N_("seconds before marking a mail as readed.");
gchar *s = N_("Prepend");
gchar *s = N_("> \n"
              "::> \n"
              "# \n"
              "Quote# \n"
              "");
gchar *s = N_("> ");
gchar *s = N_("to each line when replying a message.");
gchar *s = N_("Empty the Garbage mailbox on exit.");
gchar *s = N_("Store a copy of outgoing messages in the Outbox mailbox.");
gchar *s = N_("Check for mail at start up.");
gchar *s = N_("label18");
gchar *s = N_("Name");
gchar *s = N_("Type");
gchar *s = N_("Name");
gchar *s = N_("E-Mail");
gchar *s = N_("_New");
gchar *s = N_("_Edit");
gchar *s = N_("_Delete");
gchar *s = N_("_Up");
gchar *s = N_("Do_wn");
gchar *s = N_("label19");
gchar *s = N_("label20");
gchar *s = N_("Create a new mailbox");
gchar *s = N_("_New Mailbox");
gchar *s = N_("Delete selected mailbox");
gchar *s = N_("_Delete Mailbox");
gchar *s = N_("Mailbox properties");
gchar *s = N_("Warning");
gchar *s = N_("The edition of mailboxes\n"
              "is really dangerous and\n"
              "might result in the lost of\n"
              "all mails of the mailbox.");
gchar *s = N_("Type:");
gchar *s = N_("Name:");
gchar *s = N_("Extra data");
gchar *s = N_("Port:");
gchar *s = N_("localhost");
gchar *s = N_("Host:");
gchar *s = N_("User:");
gchar *s = N_("Pass:");
gchar *s = N_("Db:");
